{% set name = "pyiron" %}
{% set version = "0.2.10" %}
{% set sha256 = "7848fa7cbd8d7ced0e625229c2a2d9b7c23012fcd43ed19544bc88784b9b471e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ase >=3.17
    - defusedxml >=0.5.0
    - dill >=0.3.0
    - future >=0.17.1
    - gitpython >=2.1.11
    - h5io >=0.1.1
    - h5py >=2.9.0
    - matplotlib-base >=2.2.4
    - mendeleev >=0.5.1
    - numpy >=1.16.4
    - pandas >=0.24.2
    - pathlib2 >=2.3.4
    - phonopy >=2.3.2
    - psutil >=5.6.3
    - pyfileindex >=0.0.4
    - pysqa >=0.0.7
    - pytables >=3.5.1
    - scipy >=1.2.1
    - six >=1.12.0
    - spglib >=1.14.1
    - sqlalchemy >=1.3.8
    - tqdm >=4.35.0

test:
  imports:
    - pyiron
  commands:
    - pip check

about:
  home: https://pyiron.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'pyiron - an integrated development environment (IDE) for computational materials science.'
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  doc_url: https://pyiron.readthedocs.io
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - sudarsan-surendralal
