schema_version: 1

context:
  name: pyiron
  version: 0.5.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyiron-${{ version }}.tar.gz
  sha256: eaa30c944cc24da1088ca7d7ab008524fda260a97f40e0cf02619d3c1ed53f7b

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyiron_atomistics >=0.4.5

tests:
  - python:
      imports:
        - pyiron
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  homepage: https://pyiron.org
  repository: https://github.com/pyiron
  documentation: https://pyiron.readthedocs.io

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
