travis:
  secure:
    BINSTAR_TOKEN: ZyHw2yeZG96dsbzbizBLVQvn10v7FAsxVLusD0yHvbpcWy7W98hDUux+KZKoDMZJZp8AbtU6yr1HWC4pkZ011qpQnvfo5pYgyTXaFw7HRnje4hb3/Y7kRTDUSTrU3FdTsLt1wSHXpUdcKCBhqa9jHTfKprq3zoViCViJtWG/hUuwqgLbd4a5H3ajantmnICozU0X/0D4ZCwlSPpOvicvfK1vZDCIP/FWI/wPPVMC3fPb8IRs3F6ytEfc8L+qW41U4z2EV8pQYduoF4eEVCUM4EOG1B/7K193fQKY6o6KXqlYD6BNlbYUzZoHIfegra/+fJYSWvWPCR1FgrNh+V87oMKz6Xy/UTO9nQOi0jcg+PSKJ+U3G8zigFIjdY6GF6KwimjjSMby3nPWVw4vkn4SlAMW5WApYztje0i5p0JKeZl841jvCADcpZ7p8z5hDwZJFbh3AU1TDyXPXTUmJ2WyuLVd027KPZ+L8L8SgArnl/xSEc9Mhs7G61hWrYDQmeHsHrdeTjEv6az9gpOzkiZoIbjK4wjpF7cDz5mGqm1Ne7XHMpIlOz9VQnGeTJ5mgOSblN/Rq/j1XFzZCt0i0tM8e0Kt5ttKUqwfF/hhF2tINq7Gub9A8RU9E/rDsWpGuyQvTAmvhGAjmSDqhHC0uxmvspdYNJKy1H1ziGcBBNT8fZc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
